1 explicit pages:
  config/english/config_en.prc

2 implicit pages:
  /c/Panda3D-1.8.1/etc/Config.prc
  /c/Panda3D-1.8.1/etc/Confauto.prc

Traceback (most recent call last):
  File "C:\Panda3D-1.8.1\python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Panda3D-1.8.1\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\Tyler\Desktop\POTCOR-src\pirates\piratesbase\PiratesStart.py", line 34, in <module>
    PiratesBase.PiratesBase()
  File "pirates\piratesbase\PiratesBase.py", line 194, in __init__
    self.loadingScreen.showTarget(pickapirate = True)
  File "pirates\piratesbase\FancyLoadingScreen.py", line 734, in showTarget
    self._FancyLoadingScreen__setLoadingArt(screenshot)
  File "pirates\piratesbase\FancyLoadingScreen.py", line 761, in _FancyLoadingScreen__setLoadingArt
    self.currScreenshot = loader.loadModel(screenshot).findAllTextures()[0]
  File "C:\Panda3D-1.8.1\direct\showbase\Loader.py", line 170, in loadModel
    raise IOError, message
IOError: Could not load model file(s): ['d']
